const DATA_FILES={beaches:'Beaches',places:'Places to Visit',temples:'Hindu Temples',churches:'Churches',forts:'Forts',nature:'Waterfalls & Wildlife',museums:'Museums & Heritage',stays:'Where to Stay',food:'Goan Food',transport:'Getting Around Goa',restaurants:'Restaurants & Food',rentals:'Bike & Car Rental',emergency:'Emergency & Help',rules:'Tourist Rules',scams:'Scam Alerts',near_me:'Near Me',nightlife:'Nightlife',shopping:'Shopping',money:'Money & Banking'};
const ICONS={beaches:'🏖️',places:'🔭',temples:'🛕',churches:'⛪',forts:'🏰',nature:'🦌',museums:'🏛️',stays:'🏨',food:'🍲',transport:'🚌',restaurants:'🍽️',rentals:'🏍️',emergency:'✚',rules:'⚠️',scams:'🛡️',near_me:'⌖',nightlife:'🌙',shopping:'🛍️',money:'🏦'};
const COLORS=['c1','c2','c3','c4','c5','c6','c7','c8','c9','c10','c11','c12','c13','c14','c15','c16','c17','c18','c19','c20'];
const FALLBACK={beaches:'images/beaches.svg',places:'images/places.svg',temples:'images/temples.svg',churches:'images/churches.svg',forts:'images/forts.svg',nature:'images/nature.svg',museums:'images/museums.svg',stays:'images/stays.svg',food:'images/food.svg',transport:'images/transport.svg',restaurants:'images/restaurants.svg',rentals:'images/rentals.svg',emergency:'images/emergency.svg',rules:'images/rules.svg',scams:'images/scams.svg',near_me:'images/near_me.svg',nightlife:'images/nightlife.svg',shopping:'images/shopping.svg',money:'images/money.svg'};
let datasets={},currentKey=null,currentItems=[],favorites=JSON.parse(localStorage.getItem('goaGuideFavorites')||'[]');
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function showPage(id){$$('.page').forEach(p=>p.classList.remove('active'));$('#'+id).classList.add('active');window.scrollTo(0,0)}
function maps(q){return 'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q||'Goa')}
function safeImg(item){return item.image&&item.image.trim()?item.image:FALLBACK[currentKey]||'images/places.svg'}
function isFav(id){return favorites.includes(id)}
function toggleFav(id){favorites=isFav(id)?favorites.filter(x=>x!==id):[...favorites,id];localStorage.setItem('goaGuideFavorites',JSON.stringify(favorites));renderList();updateDetailHeart(id)}
function updateDetailHeart(id){const v=isFav(id);$('#detailFav').textContent=v?'♥':'♡';$('#detailHeart').textContent=v?'♥':'♡';$('#detailHeart').style.color=v?'#e34b63':'#74808a'}
function categoryCard(key,i){return `<button class="category-card" data-key="${key}"><span class="cat-icon ${COLORS[i%COLORS.length]}">${ICONS[key]}</span><strong>${DATA_FILES[key]}</strong></button>`}
function renderHome(){const keys=Object.keys(DATA_FILES);$('#categoryGrid').innerHTML=keys.map((k,i)=>categoryCard(k,i)).join('');$$('.category-card').forEach(b=>b.onclick=()=>openListing(b.dataset.key))}
function sectionSubtitle(key){const map={beaches:'Famous beaches with clear waters, golden sand and vibrant nightlife.',places:'Explore famous churches, forts, waterfalls and heritage sites.',temples:'Beautiful temples with rich history and culture.',food:'Taste authentic Goan cuisine and local favourites.',stays:'Find hotels, resorts, guest houses and places to stay.',emergency:'Important numbers and government services.'};return map[key]||'Explore useful information for travelling around Goa.'}
function openListing(key){currentKey=key;const d=datasets[key];if(!d)return;currentItems=d.items||[];$('#listingIcon').textContent=ICONS[key];$('#listingTitle').textContent=key==='places'?'Places to Visit in Goa':(key==='emergency'?'Emergency & Help':(d.title||DATA_FILES[key]));$('#listingSubtitle').textContent=sectionSubtitle(key);renderChips();renderList();showPage('listingPage');}
function renderChips(){let tags=[];currentItems.forEach(x=>(x.tags||[]).forEach(t=>{if(!tags.includes(t))tags.push(t)}));const preferred=['All','North Goa','South Goa','Ponda','Family Friendly','Seafood','Traditional','Restaurants','Budget'];let chips=preferred.filter(x=>x==='All'||currentItems.some(i=>(i.region||'').toLowerCase().includes(x.toLowerCase())||(i.tags||[]).some(t=>t.toLowerCase().includes(x.toLowerCase()))));if(!chips.length)chips=['All'];$('#chips').innerHTML=chips.map((x,i)=>`<button class="chip ${i===0?'active':''}" data-chip="${x}">${x}</button>`).join('');$$('.chip').forEach(c=>c.onclick=()=>{$$('.chip').forEach(x=>x.classList.remove('active'));c.classList.add('active');filterList(c.dataset.chip)})}
function filterList(chip){const q=($('#listSearch').value||'').toLowerCase();let items=currentItems;if(chip&&chip!=='All')items=items.filter(i=>(i.region||'').toLowerCase().includes(chip.toLowerCase())||(i.tags||[]).some(t=>t.toLowerCase().includes(chip.toLowerCase())));if(q)items=items.filter(i=>JSON.stringify(i).toLowerCase().includes(q));renderItems(items)}
function renderList(){filterList($('.chip.active')?.dataset.chip||'All')}
function renderItems(items){if(!items.length){$('#listItems').innerHTML='<div style="padding:30px;text-align:center;color:#74808a;font-size:12px">No matching places found.</div>';return}$('#listItems').innerHTML=items.map(item=>`<article class="place-row"><img class="thumb" src="${safeItemImg(item)}" alt="${esc(item.name)}" loading="lazy" onerror="this.src='${FALLBACK[currentKey]}'"><div class="place-main"><div class="place-top"><div class="place-name">${esc(item.name)}</div><button class="heart" data-fav="${item.id}" aria-label="Favorite">${isFav(item.id)?'♥':'♡'}</button></div><div class="place-location">${esc(item.location||'Goa')}</div><div class="rating">${item.rating?`<span class="star">★</span> ${esc(String(item.rating))}`:'Goa Guide'} </div><p class="place-desc">${esc(item.description||'Goa travel information.')}</p><div class="row-actions"><button class="mini-btn primary" data-open="${item.id}">View Details</button><a class="mini-btn" href="${item.maps_url||maps(item.maps_query||item.name)}" target="_blank" rel="noopener">Directions</a></div></div></article>`).join('');$$('[data-open]').forEach(b=>b.onclick=()=>openDetail(currentItems.find(x=>x.id===b.dataset.open)));$$('[data-fav]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleFav(b.dataset.fav)})}
function safeItemImg(item){return item.image&&item.image.trim()?item.image:(FALLBACK[currentKey]||'images/places.svg')}
function openDetail(item){if(!item)return;$('#detailName').textContent=item.name;$('#detailMeta').textContent=(item.rating?`★ ${item.rating} · `:'')+(item.location||'Goa');$('#detailDescription').textContent=item.description||'Information about this Goa place.';$('#detailPhoto').src=safeItemImg(item);$('#detailPhoto').onerror=()=>$('#detailPhoto').src=FALLBACK[currentKey];$('#detailDirections').href=item.maps_url||maps(item.maps_query||item.name);const facts=[];facts.push(['⌖','Location',item.location||'Goa']);if(item.region)facts.push(['◉','Area',item.region+' Goa']);if(item.phone)facts.push(['☎','Phone',item.phone]);if(item.tags?.length)facts.push(['▣','Category',item.tags.join(' · ')]);if(item.source)facts.push(['ⓘ','Source',item.source]);$('#detailFacts').innerHTML=facts.map(f=>`<div class="fact"><div class="fact-icon">${f[0]}</div><div><strong>${f[1]}</strong><span>${esc(f[2])}</span></div></div>`).join('');$('#detailTopTitle')?.remove();updateDetailHeart(item.id);$('#detailFav').onclick=()=>toggleFav(item.id);showPage('detailPage')}
function renderEmergency(){const items=datasets.emergency?.items||[];const priority=[['Police','100','em-blue'],['Ambulance','108','em-red'],['Fire Brigade','101','em-orange'],['Tourist Helpline','1364','em-green']];$('#emergencyGrid').innerHTML=priority.map(x=>`<div class="em-card ${x[2]}"><a href="tel:${x[1]}"><div class="em-label">${x[0]}</div><div class="em-number">${x[1]}</div></a></div>`).join('');$('#emergencyList').innerHTML=items.map(i=>`<div class="service-row"><div class="service-icon">✚</div><div class="service-info"><div class="service-name">${esc(i.name)}</div><div class="service-loc">${esc(i.description||i.location||'Goa')}</div></div>${i.phone?`<a class="call-btn" href="tel:${i.phone}">Call</a>`:''}</div>`).join('')}
function renderNear(){const items=datasets.near_me?.items||[];$('#nearGrid').innerHTML=items.map((i,n)=>`<div class="near-card"><div class="near-card-icon">${['🏥','💊','👮','🚑','⛽','⚡','🏧','🚻','🅿️','🍽️','🛒','🏨','🏍️','🚗','🚌','🚆','⛴️','🛕','⛪','🏖️'][n%20]}</div><strong>${esc(i.name)}</strong><a href="${i.maps_url||maps(i.maps_query||i.name)}" target="_blank" rel="noopener">Find near me →</a></div>`).join('')}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function load(){for(const k of Object.keys(DATA_FILES)){try{datasets[k]=await fetch(`data/${k}.json`).then(r=>r.json())}catch(e){datasets[k]={items:[],title:DATA_FILES[k]}}}renderHome();renderEmergency();renderNear()}
$('#listingBack').onclick=()=>showPage('homePage');$('#detailBack').onclick=()=>showPage('listingPage');$('#emergencyBack').onclick=()=>showPage('homePage');$('#listingMap').onclick=()=>window.open(maps($('#listingTitle').textContent+' Goa'),'_blank');
$('#listSearch').oninput=()=>filterList($('.chip.active')?.dataset.chip||'All');
$('#globalSearch').oninput=e=>{const q=e.target.value.trim().toLowerCase();if(q.length<2)return;const found=[];Object.entries(datasets).forEach(([k,d])=>(d.items||[]).forEach(i=>{if(JSON.stringify(i).toLowerCase().includes(q))found.push({...i,__key:k})}));if(found.length){currentKey=found[0].__key;currentItems=found;$('#listingTitle').textContent='Search Results';$('#listingSubtitle').textContent=`${found.length} places found`;$('#listingIcon').textContent='⌕';$('#chips').innerHTML='<button class="chip active">All</button>';renderItems(found);showPage('listingPage')}};
$$('.nav-item').forEach(b=>b.onclick=()=>{const n=b.dataset.nav;$$('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(n==='home'){showPage('homePage')}else if(n==='near'){showPage('nearPage')}else if(n==='explore'){showPage('homePage');$('#globalSearch').focus()}else if(n==='favorites'){const all=[];Object.entries(datasets).forEach(([k,d])=>(d.items||[]).forEach(i=>{if(isFav(i.id))all.push({...i,__key:k})}));currentKey=all[0]?.__key||'places';currentItems=all;$('#listingTitle').textContent='Favorites';$('#listingSubtitle').textContent=all.length+' saved places';$('#listingIcon').textContent='♥';$('#chips').innerHTML='<button class="chip active">All</button>';renderItems(all);showPage('listingPage')}else{showPage('homePage');toast('More sections are available from Explore Goa')}});
$('#searchBtn').onclick=()=>{showPage('homePage');setTimeout(()=>$('#globalSearch').focus(),50)};$('#menuBtn').onclick=()=>toast('Choose a category below');
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1800)}
load();
