const CATALOG=[{"slug": "beaches", "icon": "🏖️", "title": "Beaches"}, {"slug": "places", "icon": "📍", "title": "Places to Visit"}, {"slug": "temples", "icon": "🛕", "title": "Hindu Temples"}, {"slug": "churches", "icon": "⛪", "title": "Churches"}, {"slug": "forts", "icon": "🏰", "title": "Forts"}, {"slug": "nature", "icon": "💧", "title": "Waterfalls & Wildlife"}, {"slug": "museums", "icon": "🏛️", "title": "Museums & Heritage"}, {"slug": "stays", "icon": "🏨", "title": "Where to Stay"}, {"slug": "food", "icon": "🍛", "title": "Must-Try Goan Food"}, {"slug": "transport", "icon": "🗺️", "title": "Getting Around Goa"}, {"slug": "restaurants", "icon": "🍴", "title": "Restaurants & Food Places"}, {"slug": "rentals", "icon": "🏍️", "title": "Bike & Car Rental"}, {"slug": "emergency", "icon": "🚨", "title": "Emergency & Government Help"}, {"slug": "rules", "icon": "⚠️", "title": "Important Tourist Rules"}, {"slug": "scams", "icon": "🛡️", "title": "Tourist Scam Alerts"}, {"slug": "near_me", "icon": "📍", "title": "Important Places Near Me"}, {"slug": "nightlife", "icon": "🌙", "title": "Things To Do / Nightlife"}, {"slug": "shopping", "icon": "🛍️", "title": "Goa Shopping Guide"}, {"slug": "money", "icon": "💰", "title": "Money & Banking"}];
const grid=document.querySelector('#grid'),home=document.querySelector('#home'),detail=document.querySelector('#detail');
const dt=document.querySelector('#detailTitle'),dd=document.querySelector('#detailDesc'),di=document.querySelector('#detailImg'),items=document.querySelector('#items');
const search=document.querySelector('#search'),filter=document.querySelector('#filter');let current=[],currentSlug='';
function fallback(s){return `images/${s}.svg`}
function renderHome(q=''){grid.innerHTML='';const x=q.toLowerCase();CATALOG.filter(c=>!x||(`${c.title} ${c.slug}`).toLowerCase().includes(x)).forEach(c=>{let a=document.createElement('article');a.className='card';a.innerHTML=`<img loading="lazy" src="${fallback(c.slug)}" alt="${c.title}"><div class="body"><div class="ic">${c.icon}</div><h3>${c.title}</h3><p>Explore real Goa information and practical tools.</p></div>`;a.onclick=()=>openCat(c);grid.appendChild(a)})}
async function openCat(c){currentSlug=c.slug;home.style.display='none';detail.style.display='block';dt.textContent=c.icon+' '+c.title;dd.textContent='Real-data test directory. Verify changing details before production.';di.src=fallback(c.slug);items.innerHTML='<div class="item">Loading…</div>';filter.value='';try{let r=await fetch(`data/${c.slug}.json`);let j=await r.json();current=j.items||[];renderItems()}catch(e){items.innerHTML='<div class="item">JSON could not be loaded. Use GitHub Pages or a local web server instead of file://.</div>'}scrollTo(0,0)}
function renderItems(){let q=(filter.value||'').toLowerCase();let arr=current.filter(x=>`${x.name} ${x.description} ${x.location} ${(x.tags||[]).join(' ')}`.toLowerCase().includes(q));items.innerHTML='';arr.forEach(x=>{let a=document.createElement('article');a.className='item'+(x.phone?' emergency':'');let call=x.phone?`<a class="btn" href="tel:${x.phone.replace(/[^0-9+]/g,'')}">Call ${x.phone}</a>`:'';let src=x.image_source?`<a class="btn secondary" target="_blank" href="${x.image_source}">Image/source</a>`:'';let ing=x.common_ingredients?`<div class="chips"><span class="chip">Ingredients: ${x.common_ingredients}</span></div>`:'';let warn=x.warning_signs?`<p><b>Warning signs:</b> ${x.warning_signs}</p><p><b>Protect yourself:</b> ${x.protect_yourself}</p>`:'';a.innerHTML=`<div class="itemTop"><div><h3>${x.name}</h3><div class="loc">📍 ${x.location||'Goa'}</div></div></div><p>${x.description||''}</p>${ing}${warn}<div class="actions">${call}<a class="btn" target="_blank" href="${x.maps_url}">📍 Google Maps</a>${src}</div>`;items.appendChild(a)})}
document.querySelector('#back').onclick=()=>{detail.style.display='none';home.style.display='block';search.value='';filter.value='';renderHome();scrollTo(0,0)};search.oninput=()=>renderHome(search.value);filter.oninput=renderItems;renderHome();
